info:
    component: Zuul Server

spring:
  application:
     name: zuul-server

endpoints:
    restart:
        enabled: true
    shutdown:
        enabled: true
    health:
        sensitive: false

zuul:
    ignoredServices: "*"
    routes:
        userapi:
            path: /userapi/**
            serviceId: user-service
            stripPrefix: true

server:
    port: 8763
    compression:
        enabled: true

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 5
        leaseExpirationDurationInSeconds: 5

    client:
        registryFetchIntervalSeconds: 5
        instanceInfoReplicationIntervalSeconds: 5
        initialInstanceInfoReplicationIntervalSeconds: 5
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        fetchRegistry: true

logging:
    level:
      ROOT: INFO
      org.springframework.web: INFO