# Spring properties
spring:
  thymeleaf:
    enabled: false             # Allow Thymeleaf templates to be reloaded at runtime

# Eureka Server Configuration
server:
  port: 8761

info:
  component: Discovery Server

eureka:
    instance:
          hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/